---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: genzen
  labels:
    app: genzen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genzen-backend
  template:
    metadata:
      labels:
        app: genzen-backend
    spec:
      containers:
        - name: genzen-backend
          image: genzen-backend:v01
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 8001
          env: 
            - name: CORS_ORIGINS
              value: "http://frontend-service:3000,http://localhost:3000,http://localhost:8001"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 30
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8001
            failureThreshold: 30
            periodSeconds: 10
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox:1.37
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
        - name: init-verify-redis-ready
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
            ]
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi