---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: genzen
  labels:
    app: genzen-backend
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: genzen-backend