---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: genzen-frontend
  labels:
    app: frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: genzen-api