apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: genzen
spec:
  template:
    spec:
      serviceAccountName: default-genzen
      containers:
        - name: genzen-backend
          env:
            - name: AWS_CONFIG_FILE
              value: "/dev/null"
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: "/dev/null"
            - name: AWS_SDK_LOAD_CONFIG
              value: "0"
            - name: AWS_REGION
              value: "us-east-2"
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: CLASSIFICATION_ENDPOINT
              value: "huggingface-multi-model-classification-ep"
          envFrom:
            - secretRef:
                name: backend-secrets
