---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genzen
resources:
  - ./namespace.yaml
  - ./my-service-account.yaml
  - ../../base
  - ./virtual-service.yaml

secretGenerator:
  - name: backend-secrets
    envs:
      - .env.prod.backend

images:
  - name: genzen-backend
    newName: 975049977273.dkr.ecr.us-east-2.amazonaws.com/genzen/backend
    newTag: v1.5-patch4
  - name: genzen-frontend
    newName: 975049977273.dkr.ecr.us-east-2.amazonaws.com/genzen/frontend
    newTag: v1.4

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: backend-deployment
