apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: genzen-cert
  namespace: istio-system
spec:
  secretName: genzen-info-tls
  commonName: genzen.info
  dnsNames:
  - genzen.info
  - "*.genzen.info"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer