---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genzen-backend
resources:
  - ./namespace.yaml
  - ../../base

# patches:
# - path: service-lab5-lb.yaml
#   target:
#     kind: Service
#     labelSelector: app=lab-prediction-service
    
# - path: project-lab5-lb.yaml
#   target:
#     kind: Service
#     labelSelector: app=project-prediction-service