---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genzen-backend
resources:
  - ./namespace.yaml
  - ../../base

images:
  - name: genzen-backend
    newName: genzen-backend
    newTag: v01