apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: genzen
spec:
  template:
    spec:
      containers:
        - name: genzen-backend
          envFrom:
            - secretRef:
                name: backend-secrets