---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-external-access
  namespace: genzen
spec:
  hosts:
    - "*"
  gateways:
    - frontend-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: frontend-service
            port:
              number: 3000