# cluster-config.yaml - Takes about 30 mins to create everything
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: genzen-test-06
  region: us-east-2
  version: "1.31" # 1.32 is the latest version
  tags:
    karpenter.sh/discovery: genzen-test-06

iam:
  withOIDC: true

availabilityZones:
  - us-east-2a
  - us-east-2b
  # - us-east-2c

karpenter:
  version: 'v0.20.0'

nodeGroups:
  - name: ng-spot-1
    minSize: 1
    maxSize: 2
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro", "t3.micro"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 1
  # - name: ng-spot-1
  #   instanceType: ["t2.micro", "t3.micro"]
  #   spot: true
  #   minSize: 1
  #   maxSize: 2
  #   desiredCapacity: 1
  # - name: ng-spot-2
  #   # instanceType: m5.large
  #   instanceType: ["t2.micro", "t3.micro"]
  #   spot: true
  #   minSize: 1
  #   maxSize: 2
  #   desiredCapacity: 2
