---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genzen
resources:
  - ./namespace.yaml
  - ../../base

secretGenerator:
  - name: backend-secrets
    envs:
      - .env-docker

images:
  - name: genzen-backend
    newName: genzen-backend
    newTag: v03

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: backend-deployment
